name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v4
    - name: Fetch latest data
      run: node ./scripts/fetch.js
    - name: Convert kml
      run: |-
        docker run --rm -v $(pwd):/data -w /data "ghcr.io/osgeo/gdal:alpine-small-3.10.2" ogr2ogr -f GeoJSON essential-energy.geojson essential-energy.kml
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git pull --rebase
        git push


