name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://www.ausgrid.com.au/webapi/OutageListData/GetDetailedUnplannedOutages | jq . > unplanned.json
        curl https://www.ausgrid.com.au/webapi/OutageListData/GetDetailedPlannedOutages | jq . > planned.json
        curl https://www.energex.com.au/static/Energex/energex_po_current_unplanned.geojson | jq . > energex-unplanned.geojson
        curl https://www.energex.com.au/static/Energex/energex_po_current_planned.geojson | jq . > energex-planned.geojson
        curl https://www.essentialenergy.com.au/Assets/kmz/current.kml?GTg3NudO > essential-energy.kml
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git pull --rebase
        git push


